needs_by_country = [
  {
    "Country":"IND",
    "English":6,
    "General":3,
    "Mathematics":3,
    "School Management":3,
    "Art":2,
    "Physics":2,
    "Geography":2,
    "Biology":1,
    "History":1,
    "Chemistry":1,
    "Psychology":1,
    "Music":1,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"GBR",
    "English":1,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":1,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":1,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"KEN",
    "English":0,
    "General":0,
    "Mathematics":1,
    "School Management":1,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":1,
    "Psychology":1,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":1,
    "Citizenship":0,
    "German":0,
    "ICT":2,
    "Italian":0
  },
  {
    "Country":"ARM",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"PAK",
    "English":0,
    "General":0,
    "Mathematics":1,
    "School Management":0,
    "Art":1,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":1,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":1,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":1,
    "Italian":0
  },
  {
    "Country":"PHL",
    "English":1,
    "General":0,
    "Mathematics":0,
    "School Management":1,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":1,
    "History":0,
    "Chemistry":0,
    "Psychology":1,
    "Music":1,
    "PE":0,
    "Spanish":1,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":1,
    "French":1,
    "Citizenship":0,
    "German":1,
    "ICT":0,
    "Italian":1
  },
  {
    "Country":"BRA",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"MYS",
    "English":2,
    "General":0,
    "Mathematics":1,
    "School Management":1,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":1,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"ESP",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":1,
    "Art":0,
    "Physics":1,
    "Geography":0,
    "Biology":1,
    "History":1,
    "Chemistry":0,
    "Psychology":0,
    "Music":1,
    "PE":1,
    "Spanish":0,
    "PHSE":1,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":1,
    "German":1,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"AFG",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"AZE",
    "English":1,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":1,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":1,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"BLZ",
    "English":0,
    "General":1,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"BWA",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":1,
    "History":1,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":1,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"CHL",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"ECU",
    "English":0,
    "General":1,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"EGY",
    "English":0,
    "General":0,
    "Mathematics":1,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":1,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"IRQ",
    "English":1,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"IRL",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"MEX",
    "English":1,
    "General":0,
    "Mathematics":0,
    "School Management":1,
    "Art":1,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":1,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"NGA",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"MMR",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"SOM",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"ZAF",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"SDN",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":1,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"SYR",
    "English":1,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"BHS",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"NLD",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"TTO",
    "English":1,
    "General":0,
    "Mathematics":1,
    "School Management":1,
    "Art":1,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":1,
    "PE":0,
    "Spanish":1,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":1,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":1,
    "Italian":0
  },
  {
    "Country":"TUR",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"ARE",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"USA",
    "English":1,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"VNM",
    "English":0,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  },
  {
    "Country":"ZWE",
    "English":1,
    "General":0,
    "Mathematics":0,
    "School Management":0,
    "Art":0,
    "Physics":0,
    "Geography":0,
    "Biology":0,
    "History":0,
    "Chemistry":0,
    "Psychology":0,
    "Music":0,
    "PE":0,
    "Spanish":0,
    "PHSE":0,
    "Religious Education":0,
    "Design & Technology":0,
    "Business":0,
    "French":0,
    "Citizenship":0,
    "German":0,
    "ICT":0,
    "Italian":0
  }
]